lista_preguntas = [
    {"pregunta": "¿Qué equipo argentino tiene más títulos de la Copa Libertadores?", 
     "respuesta_1": "River Plate", 
     "respuesta_2": "Boca Juniors", 
     "respuesta_3": "Independiente", 
     "respuesta_4": "Racing Club", 
     "respuesta_correcta": 3},

    {"pregunta": "¿En qué año debutó Lionel Messi con la selección mayor de Argentina?", 
     "respuesta_1": "2004", 
     "respuesta_2": "2005", 
     "respuesta_3": "2006", 
     "respuesta_4": "2007", 
     "respuesta_correcta": 2},

    {"pregunta": "¿Qué jugador argentino es conocido como 'El Pibe de Oro'?", 
     "respuesta_1": "Diego Maradona", 
     "respuesta_2": "Gabriel Batistuta", 
     "respuesta_3": "Juan Román Riquelme", 
     "respuesta_4": "Lionel Messi", 
     "respuesta_correcta": 1},

    {"pregunta": "¿Qué selección venció Argentina en la final del Mundial 1986?", 
     "respuesta_1": "Italia", 
     "respuesta_2": "Alemania", 
     "respuesta_3": "Brasil", 
     "respuesta_4": "Países Bajos", 
     "respuesta_correcta": 2},

    {"pregunta": "¿Qué estadio es conocido como 'La Bombonera'?", 
     "respuesta_1": "El Monumental", 
     "respuesta_2": "El Cilindro", 
     "respuesta_3": "Estadio Alberto J. Armando", 
     "respuesta_4": "Gigante de Arroyito", 
     "respuesta_correcta": 3},

    {"pregunta": "¿Cuál es el apodo del club River Plate?", 
     "respuesta_1": "Los Millonarios", 
     "respuesta_2": "Los Pibes", 
     "respuesta_3": "Los Gladiadores", 
     "respuesta_4": "Las Águilas", 
     "respuesta_correcta": 1},

    {"pregunta": "¿Qué equipo argentino es conocido como 'La Academia'?", 
     "respuesta_1": "Independiente", 
     "respuesta_2": "San Lorenzo", 
     "respuesta_3": "Racing Club", 
     "respuesta_4": "Atlético Tucumán", 
     "respuesta_correcta": 3},

    {"pregunta": "¿Quién es el máximo goleador histórico de la selección argentina?", 
     "respuesta_1": "Lionel Messi", 
     "respuesta_2": "Gabriel Batistuta", 
     "respuesta_3": "Sergio Agüero", 
     "respuesta_4": "Carlos Tévez", 
     "respuesta_correcta": 1},

    {"pregunta": "¿Qué selección venció Argentina en la final de la Copa América 2021?", 
     "respuesta_1": "Brasil", 
     "respuesta_2": "Chile", 
     "respuesta_3": "Uruguay", 
     "respuesta_4": "Colombia", 
     "respuesta_correcta": 1},

    {"pregunta": "¿Qué club es conocido como 'El Rojo'?", 
     "respuesta_1": "River Plate", 
     "respuesta_2": "San Lorenzo", 
     "respuesta_3": "Independiente", 
     "respuesta_4": "Racing Club", 
     "respuesta_correcta": 3}
]